// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCsGv1qqUSiQ-0XsutK_gA4yJdUrbUIok',
    appId: '1:312113414264:web:51a1723f2ed733335ded8d',
    messagingSenderId: '312113414264',
    projectId: 'renkon-tech',
    authDomain: 'renkon-tech.firebaseapp.com',
    storageBucket: 'renkon-tech.firebasestorage.app',
    measurementId: 'G-Z988X1WMB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHPGdCLGSAgpUx59DKI9A5tmtJknLlcRs',
    appId: '1:312113414264:android:57148b26be1d917e5ded8d',
    messagingSenderId: '312113414264',
    projectId: 'renkon-tech',
    storageBucket: 'renkon-tech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXArqyar3xGmwTCYYhcc9yNSD3767CjOA',
    appId: '1:312113414264:ios:9ef19a865d580b6c5ded8d',
    messagingSenderId: '312113414264',
    projectId: 'renkon-tech',
    storageBucket: 'renkon-tech.firebasestorage.app',
    iosBundleId: 'com.example.nexafood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXArqyar3xGmwTCYYhcc9yNSD3767CjOA',
    appId: '1:312113414264:ios:9ef19a865d580b6c5ded8d',
    messagingSenderId: '312113414264',
    projectId: 'renkon-tech',
    storageBucket: 'renkon-tech.firebasestorage.app',
    iosBundleId: 'com.example.nexafood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCsGv1qqUSiQ-0XsutK_gA4yJdUrbUIok',
    appId: '1:312113414264:web:b5c4a8e53c6cc0c75ded8d',
    messagingSenderId: '312113414264',
    projectId: 'renkon-tech',
    authDomain: 'renkon-tech.firebaseapp.com',
    storageBucket: 'renkon-tech.firebasestorage.app',
    measurementId: 'G-Q653EXFE2P',
  );
}
